var relations = 
[{n: 1, country: "Brasil"},
{n: 1, country: "Colombia"},
{n: 1, country: "México"},
{n: 1, country: "Peru"},
{n: 2, country: "Antilhas Holandesas"},
{n: 2, country: "Brasil"},
{n: 2, country: "Colombia"},
{n: 2, country: "México"},
{n: 4, country: "Brasil"},
{n: 4, country: "Chile"},
{n: 4, country: "Colombia"},
{n: 4, country: "El Salvador"},
{n: 4, country: "Guatemala"},
{n: 4, country: "México"},
{n: 4, country: "Peru"},
{n: 5, country: "Brasil"},
{n: 5, country: "Chile"},
{n: 5, country: "Colombia"},
{n: 5, country: "Guatemala"},
{n: 6, country: "Brasil"},
{n: 6, country: "Colombia"},
{n: 6, country: "Costa Rica"},
{n: 6, country: "El Salvador"},
{n: 6, country: "México"},
{n: 7, country: "Brasil"},
{n: 7, country: "Colombia"},
{n: 7, country: "Costa Rica"},
{n: 7, country: "Dominican Republic"},
{n: 7, country: "México"},
{n: 9, country: "Brasil"},
{n: 9, country: "Chile"},
{n: 9, country: "Colombia"},
{n: 9, country: "Dominican Republic"},
{n: 9, country: "Guatemala"},
{n: 9, country: "México"},
{n: 10, country: "Antilhas Holandesas"},
{n: 10, country: "Bolívia"},
{n: 10, country: "Brasil"},
{n: 10, country: "Chile"},
{n: 10, country: "Colombia"},
{n: 10, country: "Costa Rica"},
{n: 10, country: "Guatemala"},
{n: 10, country: "Honduras"},
{n: 10, country: "México"},
{n: 10, country: "Panamá"},
{n: 10, country: "Peru"},
{n: 12, country: "Argentina"},
{n: 12, country: "Antilhas Holandesas"},
{n: 12, country: "Brasil"},
{n: 12, country: "Colombia"},
{n: 15, country: "Argentina"},
{n: 15, country: "Brasil"},
{n: 15, country: "Chile"},
{n: 15, country: "Paraguai"},
{n: 16, country: "Brasil"},
{n: 16, country: "Chile"},
{n: 16, country: "Colombia"},
{n: 16, country: "Dominican Republic"},
{n: 16, country: "Guatemala"},
{n: 16, country: "Honduras"},
{n: 16, country: "México"},
{n: 16, country: "Panamá"},
{n: 16, country: "Peru"},
{n: 17, country: "Antilhas Holandesas"},
{n: 17, country: "Brasil"},
{n: 17, country: "Colombia"},
{n: 17, country: "Dominican Republic"},
{n: 17, country: "Guatemala"},
{n: 17, country: "México"},
{n: 18, country: "Argentina"},
{n: 18, country: "Bolívia"},
{n: 18, country: "Brasil"},
{n: 18, country: "Chile"},
{n: 18, country: "Colombia"},
{n: 18, country: "Costa Rica"},
{n: 18, country: "Guatemala"},
{n: 18, country: "Honduras"},
{n: 18, country: "México"},
{n: 18, country: "Panamá"},
{n: 18, country: "Paraguai"},
{n: 19, country: "Brasil"},
{n: 19, country: "Chile"},
{n: 19, country: "Colombia"},
{n: 19, country: "El Salvador"},
{n: 19, country: "Guatemala"},
{n: 19, country: "México"},
{n: 19, country: "Peru"},
{n: 20, country: "Argentina"},
{n: 20, country: "Bolívia"},
{n: 20, country: "Brasil"},
{n: 20, country: "Colombia"},
{n: 21, country: "Argentina"},
{n: 21, country: "Antilhas Holandesas"},
{n: 21, country: "Brasil"},
{n: 21, country: "Colombia"},
{n: 23, country: "Brasil"},
{n: 23, country: "Chile"},
{n: 23, country: "Colombia"},
{n: 23, country: "México"},
{n: 24, country: "Brasil"},
{n: 24, country: "Costa Rica"},
{n: 24, country: "Estados Unidos"},
{n: 29, country: "Barbados"},
{n: 29, country: "Brasil"},
{n: 29, country: "Costa Rica"},
{n: 29, country: "Guatemala"},
{n: 31, country: "Brasil"},
{n: 31, country: "Colombia"},
{n: 31, country: "Costa Rica"},
{n: 32, country: "Brasil"},
{n: 32, country: "Costa Rica"},
{n: 32, country: "El Salvador"},
{n: 32, country: "Guatemala"},
{n: 32, country: "México"},
{n: 33, country: "Brasil"},
{n: 33, country: "Chile"},
{n: 33, country: "Colombia"},
{n: 33, country: "Costa Rica"},
{n: 33, country: "Dominican Republic"},
{n: 33, country: "Guatemala"},
{n: 33, country: "México"},
{n: 33, country: "Peru"},
{n: 33, country: "Estados Unidos"},
{n: 34, country: "Antilhas Holandesas"},
{n: 34, country: "Bolívia"},
{n: 34, country: "Brasil"},
{n: 34, country: "Chile"},
{n: 34, country: "Colombia"},
{n: 34, country: "Costa Rica"},
{n: 34, country: "El Salvador"},
{n: 34, country: "Guatemala"},
{n: 34, country: "México"},
{n: 34, country: "Panamá"},
{n: 35, country: "Antilhas Holandesas"},
{n: 35, country: "Brasil"},
{n: 35, country: "Colombia"},
{n: 35, country: "Costa Rica"},
{n: 35, country: "México"},
{n: 35, country: "Panamá"},
{n: 38, country: "Brasil"},
{n: 38, country: "Colombia"},
{n: 38, country: "Guatemala"},
{n: 38, country: "Panamá"},
{n: 38, country: "Paraguai"},
{n: 39, country: "Brasil"},
{n: 39, country: "Chile"},
{n: 39, country: "Colombia"},
{n: 39, country: "Guatemala"},
{n: 39, country: "México"},
{n: 39, country: "Paraguai"},
{n: 40, country: "Brasil"},
{n: 40, country: "Chile"},
{n: 40, country: "Colombia"},
{n: 40, country: "Costa Rica"},
{n: 40, country: "Guatemala"},
{n: 40, country: "México"},
{n: 41, country: "Argentina"},
{n: 41, country: "Brasil"},
{n: 41, country: "Chile"},
{n: 41, country: "Colombia"},
{n: 41, country: "México"},
{n: 46, country: "Bolívia"},
{n: 46, country: "Brasil"},
{n: 46, country: "Guatemala"},
{n: 46, country: "Peru"},
{n: 47, country: "Bolívia"},
{n: 47, country: "Brasil"},
{n: 47, country: "Chile"},
{n: 47, country: "Costa Rica"},
{n: 47, country: "Guatemala"},
{n: 47, country: "Honduras"},
{n: 47, country: "México"},
{n: 48, country: "Brasil"},
{n: 48, country: "Chile"},
{n: 48, country: "Costa Rica"},
{n: 48, country: "Guatemala"},
{n: 48, country: "Honduras"},
{n: 50, country: "Brasil"},
{n: 50, country: "Colombia"}];

var x = relations.reduce(function (accum, r) {
  if (!accum[r.n]) {
    accum[r.n] = {key: r.n, dict:{
      key: 'countries', string: []}
    };
  }
  accum[r.n].dict.string.push(r.country);
  return accum;
}, {});

var arr = [];

for (var skill in x) {
  if (x.hasOwnProperty(skill)) {
    arr.push(x[skill]);
  }
}

console.log(JSON.stringify({plist:{dict: arr}}));