#!/bin/bash

#CACHE_PATH="/var/www/vhosts/aggregator.worldskills.org/httpdocs/aggregator/cache/"
#CACHE_COLLECTIONS_PATH="/var/www/vhosts/aggregator.worldskills.org/httpdocs/aggregator/cache_collections/"

CACHE_PATH="cache/"
CACHE_PATH_STAR="cache/*.gz"
CACHE_PATH_SKILLS="cache/data-skills-*json.gz"
CACHE_COLLECTIONS_PATH="cache_collections/"
BASE_URL="http://aggregator.worldskills.org/"
#BASE_URL="http://localhost/~joni/WorldSkills-Mobile-iOS/Aggregator/"

echo "Generating generic files..."
curl $BASE_URL"aggregator/data-event.php"
curl $BASE_URL"aggregator/data-event-schedule.php"
curl $BASE_URL"aggregator/data-sectors.php"
curl $BASE_URL"aggregator/data-sponsors.php"
curl $BASE_URL"aggregator/data-venue.php"
curl $BASE_URL"aggregator/data-local-push.php"
curl $BASE_URL"aggregator/data-news.php"
curl $BASE_URL"aggregator/data-photos.php"
curl $BASE_URL"aggregator/data-videos.php"
curl $BASE_URL"aggregator/data-feedback.php"
curl $BASE_URL"aggregator/data-uploads.php"

echo "Generating skill specific files"
curl $BASE_URL"aggregator/data-skill-specific.php?skill_number=[01-45]"
curl $BASE_URL"aggregator/data-skill-specific.php?skill_number=D1"
curl $BASE_URL"aggregator/data-all-skills.php?f=1"
curl $BASE_URL"aggregator/data-full.php?f=1"
curl $BASE_URL"aggregator/data-generic.php"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=03"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=04"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=05"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=06"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=07"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=08"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=09"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=10"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=11"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=12"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=13"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=14"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=15"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=16"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=17"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=18"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=19"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=20"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=21"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=22"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=23"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=24"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=25"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=26"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=27"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=28"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=29"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=30"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=31"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=32"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=33"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=34"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=35"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=36"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=37"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=38"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=39"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=40"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=41"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=42"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=43"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=44"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=45"
#lynx -dump BASE_URL"aggregator/data-skill-specific.php?skill_number=D1"

#echo "Compressing full data..."
#tar -czf $CACHE_COLLECTIONS_PATH"full-data.tar.gz" $CACHE_PATH_STAR

#echo "Compressing generic data..."
#tar --exclude "data-skills*" -czf $CACHE_COLLECTIONS_PATH"generic.tar.gz" $CACHE_PATH_STAR

#echo "Compressing skills"
#tar -czf $CACHE_COLLECTIONS_PATH"all-skills.tar.gz" $CACHE_PATH_SKILLS

